# -*- coding: utf-8 -*-
"""FINE_TUNIN_BYME.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgNgWYDpiLgT6US_pbuLTAVLes40OTrE
"""

pip install transformers peft datasets accelerate bitsandbytes trl

# from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
# import torch

from huggingface_hub import login
from google.colab import userdata

login(token=userdata.get("HF_Token"))

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/mt5-small"   # multilingual T5 (supports Hindi + English)
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# !pip install datasets

# import datasets
from datasets import load_dataset

dataset = load_dataset("cfilt/iitb-english-hindi")

# def format_instruction(example):
#     return {
#         "text": f"### Instruction:\n{example['instruction']}\n### Input:\n{example['input']}\n### Response:\n{example['output']}"
#     }

# dataset = dataset.map(format_instruction)

print(type(dataset))

# Print the dataset object to see the splits and their structures
print(dataset)

# Access a specific split (e.g., 'train')
train_split = dataset['train']

# Print the column names of the train split
print(train_split.column_names)

# Print the features (including data types) of the train split
print(train_split.features)

# Access the data from a specific column (e.g., 'translation') for the first few examples
print(train_split['translation'][:5])

def format_translation_pair(example):
    en = example["translation"]["en"]
    hi = example["translation"]["hi"]
    return {"text": f"translate English to Hindi: {en}", "labels": hi}

formatted_dataset = dataset.map(format_translation_pair)

type(formatted_dataset)

print(dataset)
print(dataset['test'].column_names)
print(dataset['train'].features)
print(dataset['train']['translation'][:5])

# 4️⃣ Tokenize dataset
def tokenize_function(example):
    model_inputs = tokenizer(
        example["text"], truncation=True, padding="max_length", max_length=128
    )
    labels = tokenizer(
        example["labels"], truncation=True, padding="max_length", max_length=128
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_datasets = formatted_dataset.map(tokenize_function, batched=True)

tokenized_datasets = formatted_dataset.map(tokenize_function, batched=True)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    bf16=True,
    logging_steps=10,
    save_strategy="epoch",
    optim="adafactor"  # Changed optimizer to adafactor
)

trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_datasets["train"],
    args=training_args,
)

trainer.train()

# Explicitly convert model parameters to bfloat16 if they are still float32
for param in model.parameters():
    if param.dtype == torch.float32:
        param.data = param.data.to(torch.bfloat16)

print("Model parameters converted to bfloat16 where necessary.")

# 6️⃣ Save model
trainer.save_model("./mt5-english-hindi")

tokenizer.save_pretrained("./mt5-english-hindi")

# 7️⃣ Inference
from transformers import pipeline

translator = pipeline("translation", model="./mt5-english-hindi", tokenizer="./mt5-english-hindi")

text = "What is your name?"
result = translator(text)
print("🔹 English:", text)
print("🔹 Hindi:", result[0]["translation_text"])

"""BECAUSE NOT FULLY TRAINED

# LORA CODE
"""

# ==========================================================
# 🧱 LoRA Fine-Tuning for Translation (mt5-small)
# ==========================================================
!pip install transformers peft datasets accelerate bitsandbytes trl -q

from huggingface_hub import login
from google.colab import userdata
login(token=userdata.get("HF_Token"))

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTTrainer
from transformers import TrainingArguments
import torch

# 1️⃣ Load Model & Tokenizer
model_name = "google/mt5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name, device_map="auto")

# 2️⃣ Load Dataset
dataset = load_dataset("cfilt/iitb-english-hindi")

def format_translation_pair(example):
    en = example["translation"]["en"]
    hi = example["translation"]["hi"]
    return {"text": f"translate English to Hindi: {en}", "labels": hi}

formatted_dataset = dataset.map(format_translation_pair)

# 3️⃣ Tokenize
def tokenize_function(example):
    model_inputs = tokenizer(
        example["text"], truncation=True, padding="max_length", max_length=128
    )
    labels = tokenizer(
        example["labels"], truncation=True, padding="max_length", max_length=128
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_datasets = formatted_dataset.map(tokenize_function, batched=True)

# 4️⃣ Apply LoRA (Parameter-Efficient Fine-Tuning)
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["q", "v"],  # depends on architecture
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# 5️⃣ Training Arguments
training_args = TrainingArguments(
    output_dir="./results_lora",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    bf16=True,
    logging_steps=10,
    save_strategy="epoch",
    optim="adafactor"
)

# 6️⃣ Trainer
trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_datasets["train"],
    args=training_args,
)

trainer.train()

# 7️⃣ Save Fine-Tuned LoRA model
trainer.save_model("./mt5-lora-english-hindi")
tokenizer.save_pretrained("./mt5-lora-english-hindi")

# 8️⃣ Inference
from transformers import pipeline

translator = pipeline("translation", model="./mt5-lora-english-hindi", tokenizer="./mt5-lora-english-hindi")

text = "Where is the market?"
result = translator(text)
print("🔹 English:", text)
print("🔹 Hindi:", result[0]["translation_text"])

"""# QLORA CODE"""

# ==========================================================
# 🧱 QLoRA Fine-Tuning for Translation (mt5-small)
# ==========================================================
!pip install transformers peft datasets accelerate bitsandbytes trl -q

from huggingface_hub import login
from google.colab import userdata
login(token=userdata.get("HF_Token"))

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, BitsAndBytesConfig
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTTrainer
from transformers import TrainingArguments
import torch

# 1️⃣ Load Model with Quantization
model_name = "google/mt5-small"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,               # Enable 4-bit quantization
    bnb_4bit_use_double_quant=True,  # Use double quantization
    bnb_4bit_quant_type="nf4",       # NormalFloat4 quantization
    bnb_4bit_compute_dtype=torch.bfloat16
)

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

# 2️⃣ Load Dataset
dataset = load_dataset("cfilt/iitb-english-hindi")

def format_translation_pair(example):
    en = example["translation"]["en"]
    hi = example["translation"]["hi"]
    return {"text": f"translate English to Hindi: {en}", "labels": hi}

formatted_dataset = dataset.map(format_translation_pair)

# 3️⃣ Tokenize
def tokenize_function(example):
    model_inputs = tokenizer(
        example["text"], truncation=True, padding="max_length", max_length=128
    )
    labels = tokenizer(
        example["labels"], truncation=True, padding="max_length", max_length=128
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_datasets = formatted_dataset.map(tokenize_function, batched=True)

# 4️⃣ QLoRA Configuration
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["q", "v"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# 5️⃣ Training Arguments
training_args = TrainingArguments(
    output_dir="./results_qlora",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    bf16=True,
    logging_steps=10,
    save_strategy="epoch",
    optim="paged_adamw_8bit"
)

# 6️⃣ Trainer
trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_datasets["train"],
    args=training_args,
)

trainer.train()

# 7️⃣ Save QLoRA Fine-Tuned Model
trainer.save_model("./mt5-qlora-english-hindi")
tokenizer.save_pretrained("./mt5-qlora-english-hindi")

# 8️⃣ Inference
from transformers import pipeline

translator = pipeline("translation", model="./mt5-qlora-english-hindi", tokenizer="./mt5-qlora-english-hindi")

text = "Where is the school?"
result = translator(text)
print("🔹 English:", text)
print("🔹 Hindi:", result[0]["translation_text"])

"""# CSV DATASET

3. Load your CSV dataset

Assume your file is translation_data.csv with columns:

english_text,hindi_text
What is your name?,तुम्हारा नाम क्या है?
How are you?,आप कैसे हैं?
"""

1. Install required libraries
!pip install transformers peft datasets accelerate bitsandbytes trl

🧠 2. Import libraries and load model
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, TrainingArguments
from peft import LoraConfig, get_peft_model
from datasets import load_dataset
import torch

# 📥 3. Load your CSV dataset

# Assume your file is translation_data.csv with columns:

# english_text,hindi_text
# What is your name?,तुम्हारा नाम क्या है?
# How are you?,आप कैसे हैं?

dataset = load_dataset("csv", data_files="translation_data.csv")

print(dataset)
print(dataset["train"].column_names)


# You’ll see something like:

# ['english_text', 'hindi_text']

# 🧩 4. Format your dataset

# We need to make text (input) and labels (target):

def format_translation(example):
    return {
        "text": f"translate English to Hindi: {example['english_text']}",
        "labels": example["hindi_text"]
    }

formatted_dataset = dataset.map(format_translation)

# 🔠 5. Tokenize
model_name = "google/mt5-small"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

def tokenize_fn(example):
    inputs = tokenizer(example["text"], truncation=True, padding="max_length", max_length=128)
    targets = tokenizer(example["labels"], truncation=True, padding="max_length", max_length=128)
    inputs["labels"] = targets["input_ids"]
    return inputs

tokenized_datasets = formatted_dataset.map(tokenize_fn, batched=True)

# 🚀 6. Fine-tuning with LoRA
from peft import LoraConfig, get_peft_model
from transformers import Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# 🔹 LoRA configuration
lora_config = LoraConfig(
    r=16,                # rank
    lora_alpha=32,
    target_modules=["q", "v"],  # attention projections in transformer layers
    lora_dropout=0.05,
    bias="none",
    task_type="SEQ_2_SEQ_LM",
)

model = get_peft_model(model, lora_config)

training_args = TrainingArguments(
    output_dir="./mt5-lora-english-hindi",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    learning_rate=2e-4,
    logging_steps=10,
    save_strategy="epoch",
    fp16=True,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
)

trainer.train()

""" 7. Fine-tuning with QLoRA

QLoRA = LoRA + quantization (less memory)

"""

from transformers import BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
)

# Same LoRA config
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q", "v"],
    lora_dropout=0.05,
    bias="none",
    task_type="SEQ_2_SEQ_LM",
)

model = get_peft_model(model, lora_config)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
)

trainer.train()

"""COMMON FOR BOTH LORA AND QLORA"""

model.save_pretrained("./mt5-qlora-english-hindi")
tokenizer.save_pretrained("./mt5-qlora-english-hindi")

from transformers import pipeline

# 🔹 For LoRA model
translator = pipeline("translation", model="./mt5-lora-english-hindi", tokenizer="./mt5-lora-english-hindi")

# 🔹 OR for QLoRA model
# translator = pipeline("translation", model="./mt5-qlora-english-hindi", tokenizer="./mt5-qlora-english-hindi")

text = "How are you?"
result = translator(text)
print("English:", text)
print("Hindi:", result[0]["translation_text"])